---
apiVersion: v1
kind: Pod
metadata:
  name: example-kubernetes-operator
spec:
  containers:
  - name: base
    image: ubuntu:jammy-20230425
    imagePullPolicy: IfNotPresent
    command: ["bash", "-cx", "echo 'Hello, world!' && sleep 600"]
  restartPolicy: Never
